name: Test Workflow

on:
  pull_request:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install all packages
        run: npm run bootstrap
      - name: Test
        run: npm run jest
